### ISSUE TITLE
Tracker: Added, removed or replaced RPMs

### ISSUE THREAD

**Issue by trytomakeyouprivate** [iaacornus/Fedora-OSTree-Setup#53]
replace:
- [ ] toolbox with distrobox
- [ ] powerprofiles-daemon with tlp

add:
- [ ] gdb for debug traces
- [ ] cheat (nice TUI tool)
- [ ] fish + configs
- [ ] lm_sensors (dependency)
- [ ] nextcloud-client (Flatpak doesnt work integrated in Dolphin yet, maybe possible)
- [ ] pandoc
- [ ] perl-Image-ExifTool
- [ ] R rstudio-desktop (bundle, possible as option or note)
- [ ] waydroid
- [ ] unrar (Ark cant handle these files, Gnome Archive manager?)
- [ ] stacer
- [ ] selinux-policy-sandbox selinux-policy-doc
- [ ] gnome-boxes qemu qemu-kvm

remove (Kinoite)
- [ ] geoclue (constantly running in background, not needed after first install)
- [ ] baloo (crashing always, not removable by default)
- [ ] firefox, firefox-langpacks
- [ ] kwrite (obsolete using Kate)

remove (Silverblue):
- [ ]

**Comment by trytomakeyouprivate** [comment]
Geoclue cannot be removed: ```package xdg-desktop-portal-1.15.0-4.fc37.x86_64 requires geoclue2```

but it can be disabled with ```systemctl disable geoclue```

**Comment by iaacornus** [comment]
ive removed some duplicates in the list, also you can just add the recommended application in the json list and make a pr for it @trytomakeyouprivate

**Comment by iaacornus** [comment]
some are not suggestions, but rather necessity, hence i've removed it since it should be included by default in the options to be selected by user.

**Comment by iaacornus** [comment]
make a pr for this that i can include it: for programs u want to suggest for installation use this [config](https://github.com/iaacornus/Fedora-OSTree-Setup/blob/devel/config/app_for_install.json), and for removal use this [config](https://github.com/iaacornus/Fedora-OSTree-Setup/blob/devel/config/app_for_removal.json)

the code format is:

```json
"<app_id_u_will_use_for_argument>": {
        "aid": "<name_of_app>",
        "sdesc": "<simp_description_of_app>",
        "source": "<either_flatpak_or_rpm>"
    }
```

**Comment by trytomakeyouprivate** [comment]
I added the apps. I wonder how to deal with dependencies, how will the appid be used?

If its concatinated to a single rpm-ostree command, you could just write 

`gnome-boxes qemu qemu-kvm`

`R rstudio-desktop`

`virt-manager qemu qemu-kvm`

are there more dependencies for the emulators? I saw some but havent found out where they are needed.

**Comment by iaacornus** [comment]
the appid is the name of the app that you will use for installation, like the one that u will put in `rpm-ostree install` or `flatpak install`, while the `aid` is the formal name of the app, like `VSCode` is the `aid` while the `appid` is `code` (`rpm-ostree install code`)

**Comment by iaacornus** [comment]
as for the dependencies, it will be handled by the package manager
